INSERT INTO ALERGIAS (NombreDeAlergia, TipoDeAlergia) VALUES
    ('Polen', 'Respiratoria'),
    ('Mariscos', 'Alimentaria'),
    ('Penicilina', 'Medicamentosa'),
    ('Nueces', 'Alimentaria'),
    ('Polvo', 'Respiratoria'),
    ('Abejas', 'Insectos'),
    ('Ácaros', 'Respiratoria'),
    ('Lácteos', 'Alimentaria'),
    ('Eritromicina', 'Medicamentosa'),
    ('Cacao', 'Alimentaria'),
    ('Soya', 'Alimentaria'),
    ('Cacahuetes', 'Alimentaria'),
    ('Ácido acetilsalicílico', 'Medicamentosa'),
    ('Gatos', 'Animales'),
    ('Perros', 'Animales'),
    ('Moldes', 'Respiratoria'),
    ('Polvo de cereales', 'Respiratoria'),
    ('Drogas antibióticas', 'Medicamentosa'),
    ('Metamizol', 'Medicamentosa'),
    ('Algas', 'Alimentaria');
